version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "80:3333" # specify port forwarding
  nginx:
    image: nginx
    ports:
      - "8080:80" # specify port forwarding
